okta provider refactor
cloudquery/cq-provider-okta pull request #1
Opened 2021-03-03 13:37 UTC by roneli

- refactor for CQ v0.10.0
- support UserTypes
- App User/Group assignments tables

2021-03-03 14:14 UTC, roneli commented
refactor for okta provider

2021-03-03 17:26 UTC, yevgenypats requested changes
Had a few comments. I'll do another small round of CR after that one as it is a big PR.

2021-03-03 17:26 UTC, yevgenypats commented on client/client.go
> +		resp, err = resp.Next(ctx, &nextUserSet)
no err check here

2021-03-03 17:26 UTC, yevgenypats commented on client/client.go
> +		resp, err = resp.Next(ctx, &nextUserTypeSet)
err check missing

2021-03-03 17:26 UTC, yevgenypats commented on client/client.go
> +		resp, err = resp.Next(ctx, &nextUserSet)
It's missing in a lot of similar places so not putting a comments everywhere.

2021-03-03 17:26 UTC, yevgenypats commented on resources/users.go
> +//import (
why it's commented out?

2021-03-03 17:26 UTC, yevgenypats commented on provider/provider.go
> +	if p.config.Domain == "" {
I'll add also a check here `if p.config.Domain != https://<CHANGE_THIS_TO_YOUR_OKTA_DOMAIN>.okta.com` as it is a default in the yaml

2021-03-03 17:26 UTC, yevgenypats commented on resources/applications.go
> +	//Accessibility *okta.ApplicationAccessibility   `json:"accessibility,omitempty"`
what are those fields?

2021-03-03 17:26 UTC, yevgenypats commented on resources/applications.go
> +func TransformApplications(aa []okta.App) []*Application {
I suggest changing this function signature to `func TransformApplications (aa *[]okta.App)` This way it will be more efficient and the whole array won't be copied. Same in other places.

2021-03-03 17:26 UTC, yevgenypats commented on resources/applications.go
> +	a, ok := app.(*okta.Application)
Why the cast is needed? (Im not very familiar with the Okta API.)

2021-03-04 09:36 UTC, roneli commented on resources/applications.go
> +	//Accessibility *okta.ApplicationAccessibility   `json:"accessibility,omitempty"`
Fields I didn't add support yet

2021-03-04 09:38 UTC, roneli commented on resources/applications.go
> +	a, ok := app.(*okta.Application)
okta.App is an interface so there are multiple implementers, so I am casting to the correct underlying type

2021-03-04 14:21 UTC, merged